"""
Small-World Network Analysis: CBF Similarity Graphs (Schizophrenia vs Controls)

Loads pre-computed group-average adjacency matrices (schiz_matrices.npy,
control_matrices.npy — generated by cbf_correlation_analysis.py / graph_cbf 
pipeline), thresholds them into binary graphs, and tests whether each group's
network exhibits small-world topology by comparing real graph metrics against
equivalent random graphs.

Small-world networks have high clustering (like regular lattices) but short
path lengths (like random graphs) — sigma > 1 indicates small-world structure.
"""

import networkx as nx
import numpy as np

# Load group-averaged CBF similarity matrices (one value per subject was
# already averaged upstream — these are NOT raw per-subject data)
schiz_matrices = list(np.load("/data/raulab/asl2/results/matrices/schiz_matrices.npy"))
control_matrices = list(np.load("/data/raulab/asl2/results/matrices/control_matrices.npy"))

schiz_mean = np.mean(schiz_matrices, axis=0)
control_mean = np.mean(control_matrices, axis=0)


def threshold_matrix(matrix, density=0.20):
    """Convert a weighted similarity matrix into a binary graph by keeping
    only the top X% strongest connections (density = proportion kept)."""
    mat = matrix.copy()
    np.fill_diagonal(mat, 0)  # remove self-connections
    upper_tri = mat[np.triu_indices_from(mat, k=1)]
    threshold = np.percentile(upper_tri, 100 * (1 - density))
    return (mat >= threshold).astype(float), threshold


def compute_smallworld(G, n_random=100):
    """
    Compute small-world metrics (sigma, gamma, lambda) for a graph G by
    comparing it to n_random equivalent random (Erdos-Renyi) graphs.

    gamma  = real clustering / random clustering (>1 means more clustered than random)
    lambda = real path length / random path length (~1 means path length similar to random)
    sigma  = gamma / lambda (>1 indicates small-world topology)
    """
    # Restrict to the largest connected component (path length is undefined
    # if the graph has disconnected pieces)
    lcc_nodes = max(nx.connected_components(G), key=len)
    G_lcc = G.subgraph(lcc_nodes)
    real_clustering = nx.average_clustering(G_lcc)
    real_path = nx.average_shortest_path_length(G_lcc)
    n_nodes = G_lcc.number_of_nodes()
    n_edges = G_lcc.number_of_edges()

    rand_clusterings, rand_paths = [], []
    print(f"Generating {n_random} random graphs...")
    for i in range(n_random):
        # Random graph with the same number of nodes/edges as the real graph
        G_rand = nx.gnm_random_graph(n_nodes, n_edges)
        if not nx.is_connected(G_rand):
            lcc_rand = max(nx.connected_components(G_rand), key=len)
            G_rand = G_rand.subgraph(lcc_rand)
        rand_clusterings.append(nx.average_clustering(G_rand))
        rand_paths.append(nx.average_shortest_path_length(G_rand))
        if (i + 1) % 20 == 0:
            print(f"  {i+1}/{n_random} done...")

    gamma = real_clustering / np.mean(rand_clusterings)
    lambda_ = real_path / np.mean(rand_paths)
    sigma = gamma / lambda_

    print(f"Real clustering: {real_clustering:.4f}, Random: {np.mean(rand_clusterings):.4f}")
    print(f"Real path length: {real_path:.4f}, Random:
